binary_tree : binary_tree.c
	clang -W -Wall -Werror binary_tree.c -o binary_tree

binary_tree_smartptr : binary_tree_smartptr.cpp
	clang++ -std=c++14 -W -Wall -Werror binary_tree_smartptr.cpp -o binary_tree_smartptr


dag_smartptr : dag_smartptr.cpp
	clang++ -std=c++14 -W -Wall -Werror dag_smartptr.cpp -o dag_smartptr

